name: Keep Render App Awake

# on:
#   schedule:
#     - cron: '*/30 * * * *'  # Every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s https://multiple-disease-prediction-webapp-2wgd.onrender.com/ > /dev/null
